import type { INodeProperties } from 'n8n-workflow';

const showOnlyForTool = { resource: ['tool'] };

export const toolDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnlyForTool },
		options: [
			{
				name: 'Audit SPF Includes',
				value: 'spfAudit',
				action: 'Audit an SPF include chain',
				description:
					'Walk every include and redirect and report who can transitively send as the domain, with typed findings',
				routing: { request: { method: 'POST', url: '/api/tools/spf-audit' } },
			},
			{
				name: 'Check DKIM Selector',
				value: 'dkimCheck',
				action: 'Check a DKIM selector',
				description: 'Read one DKIM selector and report the key and its strength',
				routing: { request: { method: 'POST', url: '/api/tools/dkim-check' } },
			},
			{
				name: 'Check DNS Record',
				value: 'checkRecord',
				action: 'Check a DNS record',
				description:
					'Read one record at the authoritative nameservers and at public resolvers, with TTLs and whether they agree',
				routing: { request: { method: 'POST', url: '/api/tools/check-record' } },
			},
			{
				name: 'Check Propagation',
				value: 'propagation',
				action: 'Check DNS propagation',
				description:
					'Read one name from six locations on four continents and report whether a change has propagated',
				routing: { request: { method: 'POST', url: '/api/tools/propagation-check' } },
			},
			{
				name: 'Check Reverse DNS',
				value: 'reverseDns',
				action: 'Check reverse DNS for an IP',
				description: 'The PTR record of an IP address and whether it is forward-confirmed',
				routing: { request: { method: 'POST', url: '/api/tools/reverse-dns-check' } },
			},
			{
				name: 'Count SPF Lookups',
				value: 'spfCount',
				action: 'Count SPF DNS lookups',
				description: 'The DNS lookups an SPF record spends against the limit of 10, term by term',
				routing: { request: { method: 'POST', url: '/api/tools/spf-count' } },
			},
			{
				name: 'Validate DMARC Record',
				value: 'dmarcValidate',
				action: 'Validate a DMARC record',
				description: 'Parse a DMARC record and report its tags, policy, warnings and errors',
				routing: { request: { method: 'POST', url: '/api/tools/dmarc-validate' } },
			},
		],
		default: 'propagation',
	},
	// Audit SPF Includes
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'example.com',
		description: 'The domain whose SPF include chain to audit',
		displayOptions: { show: { ...showOnlyForTool, operation: ['spfAudit'] } },
		routing: { send: { type: 'body', property: 'domain' } },
	},
	// Check DKIM Selector
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'example.com',
		description: 'The signing domain (the d= value)',
		displayOptions: { show: { ...showOnlyForTool, operation: ['dkimCheck'] } },
		routing: { send: { type: 'body', property: 'domain' } },
	},
	{
		displayName: 'Selector',
		name: 'selector',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'selector1',
		description: 'The DKIM selector (the s= value)',
		displayOptions: { show: { ...showOnlyForTool, operation: ['dkimCheck'] } },
		routing: { send: { type: 'body', property: 'selector' } },
	},
	// Check DNS Record
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'example.com',
		description: 'The domain to read the record from',
		displayOptions: { show: { ...showOnlyForTool, operation: ['checkRecord'] } },
		routing: { send: { type: 'body', property: 'domain' } },
	},
	{
		displayName: 'Record Kind',
		name: 'kind',
		type: 'options',
		options: [
			{ name: 'A', value: 'a' },
			{ name: 'AAAA', value: 'aaaa' },
			{ name: 'CNAME', value: 'cname' },
			{ name: 'DMARC', value: 'dmarc' },
			{ name: 'MX', value: 'mx' },
			{ name: 'SPF', value: 'spf' },
			{ name: 'TXT', value: 'txt' },
		],
		default: 'spf',
		description: 'Which record to read. SPF and DMARC read the well-known TXT records.',
		displayOptions: { show: { ...showOnlyForTool, operation: ['checkRecord'] } },
		routing: { send: { type: 'body', property: 'kind' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...showOnlyForTool, operation: ['checkRecord'], kind: ['a', 'aaaa', 'cname', 'txt'] } },
		options: [
			{
				displayName: 'Host',
				name: 'host',
				type: 'string',
				default: '',
				placeholder: 'www',
				description: 'A host label under the domain. Omit for the apex.',
				routing: { send: { type: 'body', property: 'host' } },
			},
		],
	},
	// Check Propagation
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'www.example.com',
		description: 'The DNS name to read from every location',
		displayOptions: { show: { ...showOnlyForTool, operation: ['propagation'] } },
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Record Type',
		name: 'recordType',
		type: 'options',
		options: [
			{ name: 'A', value: 'A' },
			{ name: 'AAAA', value: 'AAAA' },
			{ name: 'CNAME', value: 'CNAME' },
			{ name: 'MX', value: 'MX' },
			{ name: 'NS', value: 'NS' },
			{ name: 'TXT', value: 'TXT' },
		],
		default: 'A',
		description: 'The record type to read',
		displayOptions: { show: { ...showOnlyForTool, operation: ['propagation'] } },
		routing: { send: { type: 'body', property: 'record_type' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...showOnlyForTool, operation: ['propagation'] } },
		options: [
			{
				displayName: 'Expected Value',
				name: 'expectedValue',
				type: 'string',
				default: '',
				description:
					'The value every location should answer with. Without it the check reports whether all locations agree.',
				routing: { send: { type: 'body', property: 'expected_value' } },
			},
		],
	},
	// Check Reverse DNS
	{
		displayName: 'IP Address',
		name: 'ip',
		type: 'string',
		required: true,
		default: '',
		placeholder: '203.0.113.10',
		description: 'The IPv4 or IPv6 address to look up',
		displayOptions: { show: { ...showOnlyForTool, operation: ['reverseDns'] } },
		routing: { send: { type: 'body', property: 'ip' } },
	},
	// Count SPF Lookups
	{
		displayName: 'Input',
		name: 'spfInput',
		type: 'options',
		options: [
			{ name: 'Domain', value: 'domain' },
			{ name: 'Record', value: 'record' },
		],
		default: 'domain',
		description: 'Count the lookups of a domain’s published SPF record, or of a record you paste',
		displayOptions: { show: { ...showOnlyForTool, operation: ['spfCount'] } },
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'example.com',
		description: 'The domain whose published SPF record to count',
		displayOptions: { show: { ...showOnlyForTool, operation: ['spfCount'], spfInput: ['domain'] } },
		routing: { send: { type: 'body', property: 'domain' } },
	},
	{
		displayName: 'SPF Record',
		name: 'record',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'v=spf1 include:_spf.example.net ~all',
		description: 'The SPF record text to count',
		displayOptions: { show: { ...showOnlyForTool, operation: ['spfCount'], spfInput: ['record'] } },
		routing: { send: { type: 'body', property: 'record' } },
	},
	// Validate DMARC Record
	{
		displayName: 'DMARC Record',
		name: 'record',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'v=DMARC1; p=none; rua=mailto:dmarc@example.com',
		description: 'The DMARC record text to validate',
		displayOptions: { show: { ...showOnlyForTool, operation: ['dmarcValidate'] } },
		routing: { send: { type: 'body', property: 'record' } },
	},
];
